language: ruby
sudo: false
addons:
  apt:
    packages:
    - bc
    - libc6:i386
    - libstdc++6:i386
    - zlib1g:i386
    - gcc-multilib
    
## Cache composer bits
cache:
  bundler: true
  directories:
    - $HOME/.buildroot-ccache
    - $TRAVIS_BUILD_DIR

before_script:
  - bash before.sh > log.txt
  - cp buildroot-bananapi-sunxi-kernel.config buildroot-2016.05/.config
  - cd buildroot-2016.05

script:
  - make >> log.txt
  
notifications:
  email: false
