language: ruby
sudo: false
addons:
  apt:
    packages:
    - bc
    - libc6:i386
    - libstdc++6:i386
    - zlib1g:i386
    - gcc-multilib
    
## Cache composer bits
cache:
  bundler: true
  directories:
    - $HOME/.buildroot-ccache

before_script:
  - wget https://buildroot.org/downloads/buildroot-2016.05.tar.gz --no-check-certificate
  - tar xf buildroot-2016.05.tar.gz
  - cp sunxi.config buildroot-2016.05/.config
  - cd buildroot-2016.05

script:
  - make
  
notifications:
  email: false
