language: ruby
sudo: false
addons:
  apt:
    packages:
    - bc
    - libc6:i386
    - libstdc++6:i386
    - zlib1g:i386
    - gcc-multilib
    
## Cache composer bits
cache:
  bundler: true
  directories:
    - $HOME/.buildroot-ccache
    - $TRAVIS_BUILD_DIR

before_script:
  - wget https://buildroot.org/downloads/buildroot-2016.05.tar.gz --no-check-certificate
  - wget https://github.com/linux-sunxi/linux-sunxi/archive/sunxi-3.4.zip --no-check-certificate
  - tar xf buildroot-2016.05.tar.gz --keep-old-files
  - tar xf sunxi-3.4.zip
  - cp buildroot-bananian-sunxi-kernel.config buildroot-2016.05/.config
  - cd buildroot-2016.05

script:
  - make > log.txt
  
notifications:
  email: false
